# Generated by Django 6.0.4 on 2026-09-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_participation', models.BooleanField(default=False)),
                ('consent_data_storage', models.BooleanField(default=False)),
                ('first_condition', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElicitationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=10)),
                ('block', models.IntegerField()),
                ('task_index', models.IntegerField()),
                ('movie_indices', models.JSONField()),
                ('ranked_indices', models.JSONField()),
                ('seconds_taken', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_index', models.IntegerField()),
                ('movie_indices', models.JSONField()),
                ('chosen_index', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=10)),
                ('mental_demand', models.IntegerField()),
                ('effort', models.IntegerField()),
                ('frustration', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='project4.participant')),
            ],
        ),
    ]
